config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'

  resources :meetings do
    resources :presentations
  end

  resources :users

  resources :sessions, :via => [:new, :create]

  get "logout" => "sessions#destroy"

end

app/models/meeting.rb
# == Schema Information
#
# Table name: meetings
#
#  id          :integer          not null, primary key
#  meet_on     :date
#  location    :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Meeting < ActiveRecord::Base

  has_many :presentations

  scope :upcomming_meetings, -> {where('meetings.meet_on > ?', [Time.zone.now])
                                .order('meetings.meet_on')}

  scope :pastcomming_meetings, -> {where('meetings.meet_on <= ?', [Time.zone.now])
                                  .order('meetings.meet_on')}

  validates :meet_on, :presence => true
  validates :location, :presence => true,
                      :length => {minimum: 4}


  def presentations_list
    unless presentations.empty?
      presentations.collect { |p| p.title }.join(', ')
    else
      'No presentations'
    end
  end


  # formatted name base on date
  def name
    meet_on.to_s(:long)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  before_filter :set_meeting, except: [:index, :new, :create]
  before_filter :admin_required, except: [:index, :show]

  def index
    unless read_fragment(:admin => is_admin?)
      @upcomming_meetings = Meeting.upcomming_meetings
    end
    @pastcomming_mettings = Meeting.pastcomming_meetings
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    if @meeting.save
      flash[:notice] = "Meeting successfully created"
      redirect_to meetings_url
    else
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update

    if @meeing.update_attributes(meeting_params)
      flash[:notice] = "Meeting successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @meeting.destroy
    expire_fragment(/\/meetings./)
    flash[:notice] = "Meeting successfully destroyed"
    redirect_to meetings_path
  end
  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:meet_on,
                                     :location,
                                     :description)
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
  def no_meeting(meetings)
    content_tag('li', 'No Meetings') unless meetings.any?
  end

  def error_messages_for(object)

  end

  def flash_notice
    unless flash[:notice].blank?
      content_tag('div', h(flash[:notice]), {:id => "flash_notice"})
    end
  end
end

app/views/meetings/_form.html.erb
<div>
  <%= f.label :meet_on %><br/>
  <%= f.date_select :meet_on %>
</div>

<div>
  <%= f.label :location %><br/>
  <%= f.text_field :location, {:size => 35, :class => "text"} %>
</div>

<div>
  <%= f.label :description %><br/>
  <%= f.text_area :description, {:rows => 4, :class => "text"} %>
</div>

app/views/meetings/_meeting.html.erb
<li>
  <%= link_to(h(meeting.name), meeting_path(meeting)) %>
  <div class="presentation_list"><%= meeting.presentations_list %></div>
</li>

app/views/meetings/edit.html.erb
<h1>Edit Meeting</h1>
<div class="form">
  <%= error_messages_for :meeting%>

  <fieldset>
    <legend>Enter Meeting Details</legend>
    <%= form_for(@meeting) do |f| %>

        <%= render :partial => 'form', :locals => {:f => f} %>

        <%= f.submit "Edit", :class => "submit" %> &nbsp;
        <%= link_to('Cancel', meeting_path(@meeting)) %>

    <% end %>
  </fieldset>
</div>

app/views/meetings/index.html.erb
<h1>Meetings</h1>

<%= flash_notice %>
<% cache(:admin => is_admin?)
<div class="meeting_list">
  <h2>Upcomming Meetings</h2>
  <ul>
    <%= render partial: "meeting", :collection => @upcomming_meetings %>
    <%= no_meeting(@upcomming_meetings) %>
  </ul>
  <% if is_admin? %>
  <p class="add"><%= link_to('Add metting', new_meeting_path) %></p>
  <% end %>
</div>
<% end %>

<div class="meeting_list">
  <h2>Past Meeting</h2>
  <ul>
    <%= render :partial => 'meeting', :collection => @pastcomming_mettings %>
  </ul>
</div>

app/views/meetings/new.html.erb
<h1>Create a New Meeting</h1>
<div class="form">
  <%= error_messages_for :meeting%>

  <fieldset>
    <legend>Enter Meeting Details</legend>
    <%= form_for(@meeting) do |f| %>

      <%= render :partial => 'form', :locals => {:f => f} %>

      <%= f.submit "Create", :class => "submit" %> &nbsp;
      <%= link_to('Cancel', meetings_path) %>

    <% end %>
  </fieldset>
</div>

app/views/meetings/show.html.erb
<h1><%= link_to "Meetings", meetings_url %>
 &rarr; <%= h @meeting.name %>
</h1>

<%= flash_notice %>

<div class="details">
  <dl>
    <dt>When :</dt><dd><%= @meeting.name %> @ 7:00pm </dd>
    <dt>Where :</dt><dd><%= h(@meeting.location) %></dd>
    <dt>Agenda :</dt><dd><%= h(@meeting.description) %></dd>
  </dl>

  <h2>Presentation</h2>
  <% if @meeting.presentations.size == 0 %>
    <p id="no_presentations">
      There are no presentations for this meeting
    </p>
  <% end %>
  <% if is_admin? %>
  <p class="add">
    <%= link_to "Add presentation", new_meeting_presentation_path(@meeting) %>
  </p>
  <% end %>
  <% if is_admin? %>
  <p class="modify">
    <%= link_to('Edit', edit_meeting_path(@meeting)) %> |
    <%= link_to('Delete', @meeting, :confirm => "Are you sure ?", :method => :delete) %>
  </p>
  <% end %>
</div>