config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'

  resources :meetings do
    resources :presentations
  end

  resources :users

  resources :sessions, :via => [:new, :create]

  get "logout" => "sessions#destroy"

end

app/models/presentation.rb
# == Schema Information
#
# Table name: presentations
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  meeting_id  :integer
#  title       :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Presentation < ActiveRecord::Base
  belongs_to :user
  belongs_to :meeting

  validates :title, :presence => true
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_filter :set_meeting
  before_filter :set_presentation, :except => [:new, :create]
  before_filter :admin_required

  def new

  end

  def create
    @presentation = Presentation.new(presentation_params)

    if @meeting.presentations << @presentation
      redirect_to_meeting("Presentation successfully created.")
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @presentation.update_attributes(presentation_params)
      redirect_to_meeting("Presentation successfully updated.")
    else
      render :edit
    end
  end

  def destroy
    @presentation.destroy
    redirect_to_meeting("Presentation successfully destroyed.")
  end

  private
  def set_meeting
    @meeting = Meeting.find(params[:meeting_id])
  end

  def set_presentation
    @presentation = @meeting.presentations.find(params[:id])
  end

  def presentation_params
    params.require(:presentation).permit(:user_id, :meeting_id, :title, :description)
  end

  def redirect_to_meeting(notice)
    flash[:notice] = notice
    redirect_to meeting_path(@meeting)
  end

end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/presentations/_form.html.erb
<div>
  <%= f.label :title %><br/>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</div>
<div>
  <%= f.label :user_id, "Presented by" %><br/>
  <%= f.collection_select(:user_id, User.all, :id, :name) %>
</div>

app/views/presentations/edit.html.erb
<h1>Edit Presentation</h1>
<div class="form">
  <%= error_messages_for :presentation %>
  <fieldset>
    <legend>Enter Presentation Details</legend>
    <%= form_for @presentation, :url => {:action => :create, :meeting_id => @meeting.id, :id => @presentation.id} do |f| %>
      <%= render :partial => 'form', :locals => {:f => f} %>
      <%= f.submit 'Submit', :class => 'submit' %> &nbsp;
      <%= link_to 'cancel', meeting_path(@meeting) %>
    <% end %>
  </fieldset>
</div>

app/views/presentations/new.html.erb
<h1>Create Presentation</h1>
<div class="form">
  <%= error_messages_for :presentation %>

  <fieldset>
    <legend>Enter Presentation Details</legend>
    <%= form_for :presentation, :url => {:action => :create, :meeting_id => @meeting.id} do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
        <%= f.submit 'Create', :class => "submit" %> &nbsp;
        <%= link_to 'Cancel', meeting_path(@meeting), :class => 'cancel' %>
    <% end %>
  </fieldset>
</div>

app/views/presentations/show.html.erb
<h2>Presentations</h2>
<ul id="presentations">
  <% @meetings.presentations.each do |presentation| %>
    <li id="presentation_<%=h(presentation.id) %>">
      <h3>
        <%= h(presentation.title) %>&nbsp;
        <span class="modify">
          (<%= link_to "Edit", edit_meeting_presentation_path(presentation) %> |
          <%= link_to "Destroy", edit_meeting_presentation_path(presentation),
                      :confirm => "Are you sure", :method => :delete %>)
        </span>
      </h3>
      <p class="user">By : <%=h presentation.user.name %></p>
      <p class="description"><%=h presentation.description %></p>
    </li>
  <% end %>
</ul>