config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'

  resources :meetings do
    resources :presentations
  end

  resources :users

  resources :sessions, :via => [:new, :create]

  get "logout" => "sessions#destroy"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TucsonRails <%= ": #{@title}" unless @title.blank? %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'screen', :media => "screen" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>">
<div id="wrapper">
  <div id="logo">
    <%= link_to_unless_current(image_tag("logo.gif", :alt => "Tuscon Rails"), root_path) %>
  </div>

  <div id="nav">
    <ul>
      <li id="nav_home">
        <%=link_to "Home", root_path %>
      </li>
      <li id="nav_meetings">
        <%= link_to "Meetings", meetings_path %>
      </li>
      <li id="nav_users">
        <%= link_to "Members", new_user_path %>
      </li>
    </ul>
    <div>
      <% if logged_in? %>
        <%= link_to "Your profile", user_path(@current_user) %>
        &nbsp;
        <%= link_to "Logout", logout_path %>
      <% else %>
        <%= link_to "Join us", new_user_path %>
        &nbsp;
        <%= link_to "Login", new_session_path %>
      <% end %>
    </div>
  </div>

  <div id="content">
    <%= yield %>
  </div>

  <div id="footer">&nbsp;</div>
</div>

</body>
</html>